# Aplica��o
spring.application.name=bex

# Banco PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/bexdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA - MUDADO PARA update (mant�m dados entre rein�cios)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL configura��es adicionais
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# H2 Console (desabilitado)
spring.h2.console.enabled=false

# Swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

# Para debug
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# Jackson
spring.jackson.default-property-inclusion=non_null

# chave secreta
api.security.token.secret=my-secret-key

# redis
spring.cache.type=redis
spring.redis.host=redis
spring.redis.port=6379
spring.cache.redis.time-to-live=3600000